PROMPT *** Suppression des polices de sécurité
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN12','EMPLOYES','EMPLOYES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN12','POLES','POLES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN12','TACHES','TACHES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN12','PROJETS','PROJET_POLICY');

-- Suppression des tables
DROP TABLE taches CASCADE CONSTRAINTS;
DROP TABLE employes CASCADE CONSTRAINTS;
DROP TABLE projets CASCADE CONSTRAINTS;
DROP TABLE poles CASCADE CONSTRAINTS;

-- Suppression des rôles
DROP ROLE ADMIN12_CHEF_PROJET;
DROP ROLE ADMIN12_CHEF_POLE;
DROP ROLE ADMIN12_EMPLOYE;
DROP ROLE ADMIN12_RH;
DROP ROLE ADMIN12_ADMIN;
