PROMPT *** Suppression des polices de sécurité
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','EMPLOYES','EMPLOYES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','POLES','POLES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','TACHES','VPD_TACHES');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','PROJETS','PROJET_POLICY');

PROMPT *** Suppression de tous les elements
DROP TABLE poles;
DROP TABLE employes;
DROP TABLE projets;
DROP TABLE taches;

