PROMPT *** Suppression des polices de sécurité
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','EMPLOYES','EMPLOYES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','POLES','POLES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','TACHES','TACHES_POLICY');
EXECUTE DBMS_RLS.DROP_POLICY('ADMIN10','PROJETS','PROJET_POLICY');

DROP CONTEXT entreprise_ctx;


-- Suppression des tables
DROP TABLE taches CASCADE CONSTRAINTS;
DROP TABLE employes CASCADE CONSTRAINTS;
DROP TABLE projets CASCADE CONSTRAINTS;
DROP TABLE poles CASCADE CONSTRAINTS;

-- Suppression des rôles
DROP ROLE ADMIN10_CHEF_PROJET;
DROP ROLE ADMIN10_CHEF_POLE;
DROP ROLE ADMIN10_EMPLOYE;
DROP ROLE ADMIN10_RH;
DROP ROLE ADMIN10_ADMIN;
